moulhit1_2/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^plates/', include('plates.urls')),
    url(r'^admin/', admin.site.urls),
]

plates/urls.py
from django.conf.urls import url

from . import views

app_name = 'plates'
urlpatterns = [

    url(r'^$', views.index, name='index'),

    # ex: /plates/5/details
    url(r'^(?P<plate_id>[0-9]+)/details/$', views.details, name='details'),

    # ex: /plates/account
    url(r'^account/$', views.account, name='account'),

    # ex: /plates/account
    url(r'^account/complete/$', views.save_account, name='save_account'),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

plates/models.py
from datetime import datetime, timedelta, time
from django.db import models

# Create your models here.
class Plate(models.Model):
    plate_number = models.CharField(max_length=75)
    latitude = models.DecimalField(max_digits=7, decimal_places=7)
    longitude = models.DecimalField(max_digits=7, decimal_places=7)
    plate_image = models.FileField(upload_to='plate_uploads/plates/')
    overview_image = models.FileField(upload_to='plate_uploads/overviews/')
    entry_date = models.DateTimeField('date published')
    truck_number = models.CharField(max_length=50)

class LicPlate(models.Model):
    plate_number = models.CharField(max_length=75)
    latitude = models.DecimalField(max_digits=12, decimal_places=7)
    longitude = models.DecimalField(max_digits=12, decimal_places=7)
    plate_image = models.FileField(upload_to='plate_uploads/plates/')
    overview_image = models.FileField(upload_to='plate_uploads/overviews/')
    entry_date = models.DateTimeField('date published')
    truck_number = models.CharField(max_length=50)

class customers(models.Model):
    email = models.CharField(max_length=75, unique=True)
    username = models.CharField(max_length=75, unique=True)
    password = models.CharField(max_length=50)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=75)
    entry_date = models.DateTimeField('date published')
    entryip = models.CharField(max_length=30)

'''
class hotlistManager(models.Manager):
    def create_hotlist(self, plate_number, customer_id, dateNow):
        #dateNow = datetime.now().date().__str__()
        hotlist = self.create(plate_number=plate_number, customer_id=customer_id, entry_date=dateNow)
        return hotlist
'''

class hotlist(models.Model):
    customer_id = models.ForeignKey(customers, on_delete=models.CASCADE)
    plate_number = models.CharField(max_length=30)
    entry_date = models.DateTimeField('date_published')
    entryip = models.CharField(max_length=30)

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

plates/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.utils.crypto import get_random_string
from datetime import datetime, timedelta, time
from django.utils import timezone
from .models import Plate, LicPlate, customers, hotlist
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from decimal import *


import random
import re
import os

# Create your views here.
def index(request):

    if 'plate_keyword' not in request.POST:
        plate_keyword = ""
    else:
        plate_keyword = request.POST['plate_keyword']

    if 'multi_plates' not in request.POST:
        multi_plates = ""
    else:
        multi_plates = request.POST['multi_plates']

    if 'page' not in request.GET:
        page = 1
    else:
        page = request.GET['page']

    lic_plates = []
    if multi_plates != "":
        get_multi_plates = multi_plates.split('\n')
        multi_plates = "'" + ("', '").join(x.strip() for x in get_multi_plates) + "'"
        lic_plates = list(LicPlate.objects.raw('select * from plates_licplate WHERE plate_number in (' + multi_plates + ')'))
    elif plate_keyword != "":
        lic_plates = LicPlate.objects.filter(plate_number=plate_keyword)
        if lic_plates:
            for plate in lic_plates:
                customer_id = 1
                dateNow = timezone.now()
                c = customers.objects.get(pk=1)
                # check if that customer already entered plate into hotlist
                hotlist_items = hotlist.objects.filter(customer_id=c).filter(plate_number=plate_keyword)
                if not hotlist_items:
                    h = hotlist(plate_number=plate_keyword, customer_id=c, entry_date=dateNow)
                    h.save()
    else:
        lic_plates = LicPlate.objects.order_by('-entry_date')

    paginator = Paginator(lic_plates, 24)

    try:
        license_plates = paginator.page(page)
    except PageNotAnInteger:
        license_plates = paginator.page(1)
    except EmptyPage:
        license_plates = paginator.page(paginator.num_pages)
    context = {'lic_plates': license_plates}
    return render(request, 'plates/index.html', context)

def details(request, plate_id):
    return HttpResponse("This is the details page")

def account(request):

    customer_id = 1
    customer = customers.objects.get(pk=customer_id)

    return render(request, 'plates/account/index.html', {'customers': customer})

def save_account(request):
    customer_id = '1'
    customer = get_object_or_404(customers, pk=customer_id)

    if 'email' not in request.POST:
        email = ""
    else:
        email = request.POST['email']

    customer.email = email
    customer.save()

    return HttpResponseRedirect(reverse('plates:account'))



'''
def index(request):
    random.seed()
    for p in LicPlate.objects.all():
        plate_number = get_random_string(length=8)
        p.plate_number = plate_number.upper()
        p.truck_number = get_random_string(length=5)
        getcontext().prec = 7
        latitude = random.randint(3400000, 4200000)
        p.latitude = Decimal(latitude) / Decimal(100000)
        longitude = random.randint(8400000, 11500000)
        p.longitude = Decimal(longitude) / Decimal(100000)
        plate_image = os.path.basename(p.plate_image.name)
        plate_image = re.sub(r'\.[a-zA-Z0-9]{3,4}', r'.jpg', plate_image)
        p.plate_image = plate_image
        overview_image = os.path.basename(p.overview_image.name)
        overview_image = re.sub(r'\.[a-zA-Z0-9]{3,4}', r'.jpg', overview_image)
        p.overview_image = overview_image
        p.save()
'''

polls/views.py
from django.shortcuts import render

import random

# Create your views here.
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import get_object_or_404, render

from .models import Question, Choice

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    '''
    random.seed()
    for c in Choice.objects.all():
        c.votes = random.randint(1,150)
        c.save()
    '''
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

plates/templates/plates/account/index.html
<h1>My Account</h1>
<hr>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'plates:save_account' %}" method="post">
    {% csrf_token %}

    Email:
    <div style="clear: both; height: 7px;" ></div>
    <input type="text" name="email" id="email" value="{{ customers.email }}" />

<input type="submit" value="Update" />
</form>

plates/templates/plates/index.html
<style>
.plates_holder {
    width: 30%;
    margin-right: 1%;
    min-height: 16px;
    float: left;
}
.search_holder {
    width: 50%;
    min-height: 16px;
    float: left;
}
a.button {
    background-color: #E6E6E6;
    padding: 4px 7px
    border: 1px solid #333;
    border-radius: 7px;
}
</style>
<h1>Plates</h1>
<hr>
    <form action="{% url 'plates:index' %}" method="post" name="frmSearch" id="frmSearch">
        <div class="search_holder">
            Search License Plate
            <div style="clear: both; height: 4px;"></div>
            <input type="text" name="plate_keyword" id="plate_keyword" value="{{ request.POST.plate_keyword }}" style="width: 200px;">
            <div style="clear: both; height: 4px;"></div>
            <a href="#" onclick="document.getElementById('frmSearch').submit()" class="button" >Search</a>
            {% csrf_token %}
        </div>
        <div class="search_holder">
            Search Multiple Plates
            <div style="clear: both; height: 4px;"></div>
            <textarea name="multi_plates" id="multi_plates" value="" style="width: 200px; height: 100px;">{{ request.POST.multi_plates }}</textarea>
            <div style="clear: both; height: 4px;"></div>
        </div>
    </form>
    <div style="clear: both; height: 0px;"></div>
<hr>
<div style="clear: both; height: 0px;"></div>
{% if lic_plates %}
    <center>
    {% if lic_plates.has_previous %}
        <a href="?page={{ lic_plates.previous_page_number }}" >previous</a>
    {% endif %}
    <span class="current" >Page {{ lic_plates.number }} of {{ lic_plates.paginator.num_pages }} </span>
    {% if lic_plates.has_next %}
        <a href="?page={{ lic_plates.next_page_number }}" >next</a>
    {% endif %}
    </center>

    <div style="clear: both; height: 12px;" ></div>

    {% for plate in lic_plates %}
        <div class="plates_holder">
            <img src="http://dummyimage.com/225/175/FFFFFF/000000" />
            <div style="clear: both; height: 7px;" ></div>
            <a href="{% url 'plates:details' plate.id %}" >{{ plate.plate_number }}</a>
            <div style="clear: both; height: 7px;" ></div>
            Date Scanned: {{ plate.entry_date|date:"m/d/Y g:i A" }}
            <div style="clear: both; height: 7px;" ></div>
        </div>
        {% if forloop.counter|divisibleby:3  %}
            <div style="clear: both; height: 25px;" ></div>
        {% endif %}
    {% endfor %}

    <center>
    <div style="clear: both; height: 12px;" ></div>
    {% if lic_plates.has_previous %}
        <a href="?page={{ lic_plates.previous_page_number }}" >previous</a>
    {% endif %}
    <span class="current" >Page {{ lic_plates.number }} of {{ lic_plates.paginator.num_pages }} </span>
    {% if lic_plates.has_next %}
        <a href="?page={{ lic_plates.next_page_number }}" >next</a>
    {% endif %}
    </center>
    <div style="clear: both; height: 30px;" ></div>

{% else %}
    <p>No Plates.</p>
{% endif %}

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}